/*
 * generated by Xtext 2.24.0
 */
package org.gemoc.monilog.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.gemoc.monilog.ide.contentassist.antlr.internal.InternalMoniLog4DSLParser;
import org.gemoc.monilog.services.MoniLog4DSLGrammarAccess;

public class MoniLog4DSLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MoniLog4DSLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MoniLog4DSLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getAppenderAccess().getAlternatives(), "rule__Appender__Alternatives");
			builder.put(grammarAccess.getLayoutAccess().getAlternatives(), "rule__Layout__Alternatives");
			builder.put(grammarAccess.getEventAccess().getAlternatives(), "rule__Event__Alternatives");
			builder.put(grammarAccess.getASTEventKindAccess().getAlternatives(), "rule__ASTEventKind__Alternatives");
			builder.put(grammarAccess.getPatternAccess().getAlternatives(), "rule__Pattern__Alternatives");
			builder.put(grammarAccess.getBoundTypeAccess().getAlternatives(), "rule__BoundType__Alternatives");
			builder.put(grammarAccess.getScopeAccess().getAlternatives(), "rule__Scope__Alternatives");
			builder.put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
			builder.put(grammarAccess.getAppenderCallArgumentAccess().getAlternatives(), "rule__AppenderCallArgument__Alternatives");
			builder.put(grammarAccess.getMoniloggerCallAccess().getAlternatives(), "rule__MoniloggerCall__Alternatives");
			builder.put(grammarAccess.getEmptyOrPropertyValueAccess().getAlternatives(), "rule__EmptyOrPropertyValue__Alternatives");
			builder.put(grammarAccess.getExpressionAccess().getAlternatives(), "rule__Expression__Alternatives");
			builder.put(grammarAccess.getPropertyValueAccess().getAlternatives(), "rule__PropertyValue__Alternatives");
			builder.put(grammarAccess.getLogLevelAccess().getAlternatives(), "rule__LogLevel__Alternatives");
			builder.put(grammarAccess.getTemporalPatternKindAccess().getAlternatives(), "rule__TemporalPatternKind__Alternatives");
			builder.put(grammarAccess.getDocumentAccess().getGroup(), "rule__Document__Group__0");
			builder.put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
			builder.put(grammarAccess.getLocalAppenderAccess().getGroup(), "rule__LocalAppender__Group__0");
			builder.put(grammarAccess.getLocalAppenderAccess().getGroup_3(), "rule__LocalAppender__Group_3__0");
			builder.put(grammarAccess.getLocalAppenderAccess().getGroup_6(), "rule__LocalAppender__Group_6__0");
			builder.put(grammarAccess.getExternalAppenderAccess().getGroup(), "rule__ExternalAppender__Group__0");
			builder.put(grammarAccess.getExternalAppenderAccess().getGroup_2(), "rule__ExternalAppender__Group_2__0");
			builder.put(grammarAccess.getLocalLayoutAccess().getGroup(), "rule__LocalLayout__Group__0");
			builder.put(grammarAccess.getLocalLayoutAccess().getGroup_2(), "rule__LocalLayout__Group_2__0");
			builder.put(grammarAccess.getExternalLayoutAccess().getGroup(), "rule__ExternalLayout__Group__0");
			builder.put(grammarAccess.getExternalLayoutAccess().getGroup_2(), "rule__ExternalLayout__Group_2__0");
			builder.put(grammarAccess.getParameterDeclVarArgsAccess().getGroup(), "rule__ParameterDeclVarArgs__Group__0");
			builder.put(grammarAccess.getParameterDeclVarArgsAccess().getGroup_1(), "rule__ParameterDeclVarArgs__Group_1__0");
			builder.put(grammarAccess.getParameterDeclVarArgsAccess().getGroup_1_1(), "rule__ParameterDeclVarArgs__Group_1_1__0");
			builder.put(grammarAccess.getParameterDeclVarArgsAccess().getGroup_1_2(), "rule__ParameterDeclVarArgs__Group_1_2__0");
			builder.put(grammarAccess.getParameterDeclNoVarArgsAccess().getGroup(), "rule__ParameterDeclNoVarArgs__Group__0");
			builder.put(grammarAccess.getParameterDeclNoVarArgsAccess().getGroup_1(), "rule__ParameterDeclNoVarArgs__Group_1__0");
			builder.put(grammarAccess.getParameterDeclNoVarArgsAccess().getGroup_1_1(), "rule__ParameterDeclNoVarArgs__Group_1_1__0");
			builder.put(grammarAccess.getMoniLoggerAccess().getGroup(), "rule__MoniLogger__Group__0");
			builder.put(grammarAccess.getMoniLoggerAccess().getGroup_3(), "rule__MoniLogger__Group_3__0");
			builder.put(grammarAccess.getMoniLoggerAccess().getGroup_4(), "rule__MoniLogger__Group_4__0");
			builder.put(grammarAccess.getMoniLoggerAccess().getGroup_8(), "rule__MoniLogger__Group_8__0");
			builder.put(grammarAccess.getMoniLoggerAccess().getGroup_8_3(), "rule__MoniLogger__Group_8_3__0");
			builder.put(grammarAccess.getMoniLoggerAccess().getGroup_12(), "rule__MoniLogger__Group_12__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0(), "rule__Event__Group_0__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_3(), "rule__Event__Group_0_3__0");
			builder.put(grammarAccess.getEventAccess().getGroup_1(), "rule__Event__Group_1__0");
			builder.put(grammarAccess.getEventAccess().getGroup_1_3(), "rule__Event__Group_1_3__0");
			builder.put(grammarAccess.getEventAccess().getGroup_1_4(), "rule__Event__Group_1_4__0");
			builder.put(grammarAccess.getEventAccess().getGroup_2(), "rule__Event__Group_2__0");
			builder.put(grammarAccess.getEventAccess().getGroup_2_3(), "rule__Event__Group_2_3__0");
			builder.put(grammarAccess.getASTEventKindAccess().getGroup_0(), "rule__ASTEventKind__Group_0__0");
			builder.put(grammarAccess.getASTEventKindAccess().getGroup_1(), "rule__ASTEventKind__Group_1__0");
			builder.put(grammarAccess.getTemporalPatternAccess().getGroup(), "rule__TemporalPattern__Group__0");
			builder.put(grammarAccess.getPatternAccess().getGroup_0(), "rule__Pattern__Group_0__0");
			builder.put(grammarAccess.getPatternAccess().getGroup_1(), "rule__Pattern__Group_1__0");
			builder.put(grammarAccess.getPatternAccess().getGroup_2(), "rule__Pattern__Group_2__0");
			builder.put(grammarAccess.getPatternAccess().getGroup_3(), "rule__Pattern__Group_3__0");
			builder.put(grammarAccess.getPatternAccess().getGroup_4(), "rule__Pattern__Group_4__0");
			builder.put(grammarAccess.getLowerBoundAccess().getGroup(), "rule__LowerBound__Group__0");
			builder.put(grammarAccess.getUpperBoundAccess().getGroup(), "rule__UpperBound__Group__0");
			builder.put(grammarAccess.getScopeAccess().getGroup_0(), "rule__Scope__Group_0__0");
			builder.put(grammarAccess.getScopeAccess().getGroup_1(), "rule__Scope__Group_1__0");
			builder.put(grammarAccess.getScopeAccess().getGroup_2(), "rule__Scope__Group_2__0");
			builder.put(grammarAccess.getScopeAccess().getGroup_3(), "rule__Scope__Group_3__0");
			builder.put(grammarAccess.getScopeAccess().getGroup_4(), "rule__Scope__Group_4__0");
			builder.put(grammarAccess.getAppenderCallAccess().getGroup(), "rule__AppenderCall__Group__0");
			builder.put(grammarAccess.getAppenderCallAccess().getGroup_3(), "rule__AppenderCall__Group_3__0");
			builder.put(grammarAccess.getAppenderCallAccess().getGroup_3_2(), "rule__AppenderCall__Group_3_2__0");
			builder.put(grammarAccess.getLayoutCallAccess().getGroup(), "rule__LayoutCall__Group__0");
			builder.put(grammarAccess.getLayoutCallAccess().getGroup_3(), "rule__LayoutCall__Group_3__0");
			builder.put(grammarAccess.getLayoutCallAccess().getGroup_3_2(), "rule__LayoutCall__Group_3_2__0");
			builder.put(grammarAccess.getEmitEventAccess().getGroup(), "rule__EmitEvent__Group__0");
			builder.put(grammarAccess.getEmitEventAccess().getGroup_3(), "rule__EmitEvent__Group_3__0");
			builder.put(grammarAccess.getEmitEventAccess().getGroup_3_2(), "rule__EmitEvent__Group_3_2__0");
			builder.put(grammarAccess.getSetVariableAccess().getGroup(), "rule__SetVariable__Group__0");
			builder.put(grammarAccess.getMoniloggerCallAccess().getGroup_0(), "rule__MoniloggerCall__Group_0__0");
			builder.put(grammarAccess.getMoniloggerCallAccess().getGroup_0_4(), "rule__MoniloggerCall__Group_0_4__0");
			builder.put(grammarAccess.getMoniloggerCallAccess().getGroup_0_4_2(), "rule__MoniloggerCall__Group_0_4_2__0");
			builder.put(grammarAccess.getMoniloggerCallAccess().getGroup_1(), "rule__MoniloggerCall__Group_1__0");
			builder.put(grammarAccess.getStreamEventAccess().getGroup(), "rule__StreamEvent__Group__0");
			builder.put(grammarAccess.getStreamEventAccess().getGroup_1(), "rule__StreamEvent__Group_1__0");
			builder.put(grammarAccess.getStreamEventAccess().getGroup_1_2(), "rule__StreamEvent__Group_1_2__0");
			builder.put(grammarAccess.getPropertyValueAccess().getGroup_0(), "rule__PropertyValue__Group_0__0");
			builder.put(grammarAccess.getPropertyValueAccess().getGroup_0_1(), "rule__PropertyValue__Group_0_1__0");
			builder.put(grammarAccess.getLanguageExpressionAccess().getGroup(), "rule__LanguageExpression__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
			builder.put(grammarAccess.getQualifiedNameWithWildcardAccess().getGroup(), "rule__QualifiedNameWithWildcard__Group__0");
			builder.put(grammarAccess.getDocumentAccess().getNameAssignment_1(), "rule__Document__NameAssignment_1");
			builder.put(grammarAccess.getDocumentAccess().getImportsAssignment_2(), "rule__Document__ImportsAssignment_2");
			builder.put(grammarAccess.getDocumentAccess().getEventsAssignment_3_0(), "rule__Document__EventsAssignment_3_0");
			builder.put(grammarAccess.getDocumentAccess().getAppendersAssignment_3_1(), "rule__Document__AppendersAssignment_3_1");
			builder.put(grammarAccess.getDocumentAccess().getLayoutsAssignment_3_2(), "rule__Document__LayoutsAssignment_3_2");
			builder.put(grammarAccess.getDocumentAccess().getMoniloggersAssignment_3_3(), "rule__Document__MoniloggersAssignment_3_3");
			builder.put(grammarAccess.getImportAccess().getImportedNamespaceAssignment_1(), "rule__Import__ImportedNamespaceAssignment_1");
			builder.put(grammarAccess.getLocalAppenderAccess().getAnnotationsAssignment_0(), "rule__LocalAppender__AnnotationsAssignment_0");
			builder.put(grammarAccess.getLocalAppenderAccess().getNameAssignment_2(), "rule__LocalAppender__NameAssignment_2");
			builder.put(grammarAccess.getLocalAppenderAccess().getParameterDeclAssignment_3_1(), "rule__LocalAppender__ParameterDeclAssignment_3_1");
			builder.put(grammarAccess.getLocalAppenderAccess().getCallsAssignment_5(), "rule__LocalAppender__CallsAssignment_5");
			builder.put(grammarAccess.getLocalAppenderAccess().getCallsAssignment_6_1(), "rule__LocalAppender__CallsAssignment_6_1");
			builder.put(grammarAccess.getExternalAppenderAccess().getNameAssignment_1(), "rule__ExternalAppender__NameAssignment_1");
			builder.put(grammarAccess.getExternalAppenderAccess().getParameterDeclAssignment_2_1(), "rule__ExternalAppender__ParameterDeclAssignment_2_1");
			builder.put(grammarAccess.getLocalLayoutAccess().getNameAssignment_1(), "rule__LocalLayout__NameAssignment_1");
			builder.put(grammarAccess.getLocalLayoutAccess().getParameterDeclAssignment_2_1(), "rule__LocalLayout__ParameterDeclAssignment_2_1");
			builder.put(grammarAccess.getLocalLayoutAccess().getCallAssignment_4(), "rule__LocalLayout__CallAssignment_4");
			builder.put(grammarAccess.getExternalLayoutAccess().getNameAssignment_1(), "rule__ExternalLayout__NameAssignment_1");
			builder.put(grammarAccess.getExternalLayoutAccess().getParameterDeclAssignment_2_1(), "rule__ExternalLayout__ParameterDeclAssignment_2_1");
			builder.put(grammarAccess.getParameterDeclVarArgsAccess().getParametersAssignment_1_0(), "rule__ParameterDeclVarArgs__ParametersAssignment_1_0");
			builder.put(grammarAccess.getParameterDeclVarArgsAccess().getParametersAssignment_1_1_1(), "rule__ParameterDeclVarArgs__ParametersAssignment_1_1_1");
			builder.put(grammarAccess.getParameterDeclVarArgsAccess().getVarArgsAssignment_1_2_1(), "rule__ParameterDeclVarArgs__VarArgsAssignment_1_2_1");
			builder.put(grammarAccess.getParameterDeclNoVarArgsAccess().getParametersAssignment_1_0(), "rule__ParameterDeclNoVarArgs__ParametersAssignment_1_0");
			builder.put(grammarAccess.getParameterDeclNoVarArgsAccess().getParametersAssignment_1_1_1(), "rule__ParameterDeclNoVarArgs__ParametersAssignment_1_1_1");
			builder.put(grammarAccess.getMoniLoggerAccess().getAnnotationsAssignment_0(), "rule__MoniLogger__AnnotationsAssignment_0");
			builder.put(grammarAccess.getMoniLoggerAccess().getNameAssignment_2(), "rule__MoniLogger__NameAssignment_2");
			builder.put(grammarAccess.getMoniLoggerAccess().getParameterDeclAssignment_3_1(), "rule__MoniLogger__ParameterDeclAssignment_3_1");
			builder.put(grammarAccess.getMoniLoggerAccess().getLevelAssignment_4_1(), "rule__MoniLogger__LevelAssignment_4_1");
			builder.put(grammarAccess.getMoniLoggerAccess().getStreamEventAssignment_7(), "rule__MoniLogger__StreamEventAssignment_7");
			builder.put(grammarAccess.getMoniLoggerAccess().getConditionsAssignment_8_2(), "rule__MoniLogger__ConditionsAssignment_8_2");
			builder.put(grammarAccess.getMoniLoggerAccess().getConditionsAssignment_8_3_1(), "rule__MoniLogger__ConditionsAssignment_8_3_1");
			builder.put(grammarAccess.getMoniLoggerAccess().getActionsAssignment_11(), "rule__MoniLogger__ActionsAssignment_11");
			builder.put(grammarAccess.getMoniLoggerAccess().getActionsAssignment_12_1(), "rule__MoniLogger__ActionsAssignment_12_1");
			builder.put(grammarAccess.getParameterAccess().getNameAssignment(), "rule__Parameter__NameAssignment");
			builder.put(grammarAccess.getEventAccess().getNameAssignment_0_2(), "rule__Event__NameAssignment_0_2");
			builder.put(grammarAccess.getEventAccess().getParameterDeclAssignment_0_3_1(), "rule__Event__ParameterDeclAssignment_0_3_1");
			builder.put(grammarAccess.getEventAccess().getKindAssignment_0_5(), "rule__Event__KindAssignment_0_5");
			builder.put(grammarAccess.getEventAccess().getRuleIDAssignment_0_6(), "rule__Event__RuleIDAssignment_0_6");
			builder.put(grammarAccess.getEventAccess().getNameAssignment_1_2(), "rule__Event__NameAssignment_1_2");
			builder.put(grammarAccess.getEventAccess().getKindAssignment_1_3_1(), "rule__Event__KindAssignment_1_3_1");
			builder.put(grammarAccess.getEventAccess().getParameterDeclAssignment_1_4_1(), "rule__Event__ParameterDeclAssignment_1_4_1");
			builder.put(grammarAccess.getEventAccess().getPatternAssignment_1_6(), "rule__Event__PatternAssignment_1_6");
			builder.put(grammarAccess.getEventAccess().getNameAssignment_2_2(), "rule__Event__NameAssignment_2_2");
			builder.put(grammarAccess.getEventAccess().getParameterDeclAssignment_2_3_1(), "rule__Event__ParameterDeclAssignment_2_3_1");
			builder.put(grammarAccess.getConditionAccess().getExpressionAssignment(), "rule__Condition__ExpressionAssignment");
			builder.put(grammarAccess.getTemporalPatternAccess().getPatternAssignment_0(), "rule__TemporalPattern__PatternAssignment_0");
			builder.put(grammarAccess.getTemporalPatternAccess().getScopeAssignment_1(), "rule__TemporalPattern__ScopeAssignment_1");
			builder.put(grammarAccess.getPatternAccess().getBoundAssignment_0_2(), "rule__Pattern__BoundAssignment_0_2");
			builder.put(grammarAccess.getPatternAccess().getEventAssignment_0_3(), "rule__Pattern__EventAssignment_0_3");
			builder.put(grammarAccess.getPatternAccess().getEventAssignment_1_2(), "rule__Pattern__EventAssignment_1_2");
			builder.put(grammarAccess.getPatternAccess().getEventAssignment_2_2(), "rule__Pattern__EventAssignment_2_2");
			builder.put(grammarAccess.getPatternAccess().getPredecessorAssignment_3_1(), "rule__Pattern__PredecessorAssignment_3_1");
			builder.put(grammarAccess.getPatternAccess().getSuccessorAssignment_3_3(), "rule__Pattern__SuccessorAssignment_3_3");
			builder.put(grammarAccess.getPatternAccess().getEventAssignment_4_1(), "rule__Pattern__EventAssignment_4_1");
			builder.put(grammarAccess.getPatternAccess().getTriggerAssignment_4_3(), "rule__Pattern__TriggerAssignment_4_3");
			builder.put(grammarAccess.getExactBoundAccess().getNAssignment(), "rule__ExactBound__NAssignment");
			builder.put(grammarAccess.getLowerBoundAccess().getNAssignment_1(), "rule__LowerBound__NAssignment_1");
			builder.put(grammarAccess.getUpperBoundAccess().getNAssignment_1(), "rule__UpperBound__NAssignment_1");
			builder.put(grammarAccess.getScopeAccess().getLowerBoundAssignment_1_2(), "rule__Scope__LowerBoundAssignment_1_2");
			builder.put(grammarAccess.getScopeAccess().getUpperBoundAssignment_2_2(), "rule__Scope__UpperBoundAssignment_2_2");
			builder.put(grammarAccess.getScopeAccess().getLowerBoundAssignment_3_2(), "rule__Scope__LowerBoundAssignment_3_2");
			builder.put(grammarAccess.getScopeAccess().getUpperBoundAssignment_3_4(), "rule__Scope__UpperBoundAssignment_3_4");
			builder.put(grammarAccess.getScopeAccess().getLowerBoundAssignment_4_2(), "rule__Scope__LowerBoundAssignment_4_2");
			builder.put(grammarAccess.getScopeAccess().getUpperBoundAssignment_4_4(), "rule__Scope__UpperBoundAssignment_4_4");
			builder.put(grammarAccess.getAppenderCallAccess().getAppenderAssignment_0(), "rule__AppenderCall__AppenderAssignment_0");
			builder.put(grammarAccess.getAppenderCallAccess().getArgsAssignment_3_1(), "rule__AppenderCall__ArgsAssignment_3_1");
			builder.put(grammarAccess.getAppenderCallAccess().getArgsAssignment_3_2_1(), "rule__AppenderCall__ArgsAssignment_3_2_1");
			builder.put(grammarAccess.getLayoutCallAccess().getLayoutAssignment_0(), "rule__LayoutCall__LayoutAssignment_0");
			builder.put(grammarAccess.getLayoutCallAccess().getArgsAssignment_3_1(), "rule__LayoutCall__ArgsAssignment_3_1");
			builder.put(grammarAccess.getLayoutCallAccess().getArgsAssignment_3_2_1(), "rule__LayoutCall__ArgsAssignment_3_2_1");
			builder.put(grammarAccess.getEmitEventAccess().getEventAssignment_0(), "rule__EmitEvent__EventAssignment_0");
			builder.put(grammarAccess.getEmitEventAccess().getArgsAssignment_3_1(), "rule__EmitEvent__ArgsAssignment_3_1");
			builder.put(grammarAccess.getEmitEventAccess().getArgsAssignment_3_2_1(), "rule__EmitEvent__ArgsAssignment_3_2_1");
			builder.put(grammarAccess.getSetVariableAccess().getVariableAssignment_2(), "rule__SetVariable__VariableAssignment_2");
			builder.put(grammarAccess.getSetVariableAccess().getValueAssignment_4(), "rule__SetVariable__ValueAssignment_4");
			builder.put(grammarAccess.getMoniloggerCallAccess().getMoniloggerAssignment_0_1(), "rule__MoniloggerCall__MoniloggerAssignment_0_1");
			builder.put(grammarAccess.getMoniloggerCallAccess().getArgsAssignment_0_4_1(), "rule__MoniloggerCall__ArgsAssignment_0_4_1");
			builder.put(grammarAccess.getMoniloggerCallAccess().getArgsAssignment_0_4_2_1(), "rule__MoniloggerCall__ArgsAssignment_0_4_2_1");
			builder.put(grammarAccess.getMoniloggerCallAccess().getMoniloggerAssignment_1_1(), "rule__MoniloggerCall__MoniloggerAssignment_1_1");
			builder.put(grammarAccess.getStreamEventAccess().getEventAssignment_0(), "rule__StreamEvent__EventAssignment_0");
			builder.put(grammarAccess.getStreamEventAccess().getValuesAssignment_1_1(), "rule__StreamEvent__ValuesAssignment_1_1");
			builder.put(grammarAccess.getStreamEventAccess().getValuesAssignment_1_2_1(), "rule__StreamEvent__ValuesAssignment_1_2_1");
			builder.put(grammarAccess.getParameterReferenceAccess().getParameterAssignment(), "rule__ParameterReference__ParameterAssignment");
			builder.put(grammarAccess.getPropertyValueAccess().getIdAssignment_0_0(), "rule__PropertyValue__IdAssignment_0_0");
			builder.put(grammarAccess.getPropertyValueAccess().getValueAssignment_0_1_1(), "rule__PropertyValue__ValueAssignment_0_1_1");
			builder.put(grammarAccess.getPropertyValueAccess().getValueAssignment_1(), "rule__PropertyValue__ValueAssignment_1");
			builder.put(grammarAccess.getLanguageExpressionAccess().getLanguageIdAssignment_0(), "rule__LanguageExpression__LanguageIdAssignment_0");
			builder.put(grammarAccess.getLanguageExpressionAccess().getExpressionAssignment_2(), "rule__LanguageExpression__ExpressionAssignment_2");
			builder.put(grammarAccess.getDocumentAccess().getUnorderedGroup_3(), "rule__Document__UnorderedGroup_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MoniLog4DSLGrammarAccess grammarAccess;

	@Override
	protected InternalMoniLog4DSLParser createParser() {
		InternalMoniLog4DSLParser result = new InternalMoniLog4DSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MoniLog4DSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MoniLog4DSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
