/*
 * generated by Xtext 2.24.0
 */
package org.gemoc.monilog.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.gemoc.monilog.parser.antlr.internal.InternalMoniLog4DSLParser;
import org.gemoc.monilog.services.MoniLog4DSLGrammarAccess;

public class MoniLog4DSLParser extends AbstractAntlrParser {

	@Inject
	private MoniLog4DSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMoniLog4DSLParser createParser(XtextTokenStream stream) {
		return new InternalMoniLog4DSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Document";
	}

	public MoniLog4DSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MoniLog4DSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
