/*
 * generated by Xtext 2.21.0
 */
package org.gemoc.monilog.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.gemoc.monilog.parser.antlr.internal.InternalMoniLogParser;
import org.gemoc.monilog.services.MoniLogGrammarAccess;

public class MoniLogParser extends AbstractAntlrParser {

	@Inject
	private MoniLogGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMoniLogParser createParser(XtextTokenStream stream) {
		return new InternalMoniLogParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Document";
	}

	public MoniLogGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MoniLogGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
