/*
 * generated by Xtext 2.24.0
 */
package org.gemoc.monilog.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MoniLog4DSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/gemoc/monilog/parser/antlr/internal/InternalMoniLog4DSL.tokens");
	}
}
