/**
 * generated by Xtext 2.22.0
 */
package org.gemoc.monilog.moniLog4DSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Append</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.gemoc.monilog.moniLog4DSL.Append#getAppender <em>Appender</em>}</li>
 * </ul>
 *
 * @see org.gemoc.monilog.moniLog4DSL.MoniLog4DSLPackage#getAppend()
 * @model
 * @generated
 */
public interface Append extends Action
{
  /**
   * Returns the value of the '<em><b>Appender</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Appender</em>' containment reference.
   * @see #setAppender(Appender)
   * @see org.gemoc.monilog.moniLog4DSL.MoniLog4DSLPackage#getAppend_Appender()
   * @model containment="true"
   * @generated
   */
  Appender getAppender();

  /**
   * Sets the value of the '{@link org.gemoc.monilog.moniLog4DSL.Append#getAppender <em>Appender</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Appender</em>' containment reference.
   * @see #getAppender()
   * @generated
   */
  void setAppender(Appender value);

} // Append
