/**
 * generated by Xtext 2.22.0
 */
package org.gemoc.monilog.moniLog4DSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Call Argument</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.gemoc.monilog.moniLog4DSL.MoniLog4DSLPackage#getCallArgument()
 * @model
 * @generated
 */
public interface CallArgument extends EObject
{
} // CallArgument
