/**
 * generated by Xtext 2.22.0
 */
package org.gemoc.monilog.moniLog4DSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Default Language Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.gemoc.monilog.moniLog4DSL.MoniLog4DSLPackage#getDefaultLanguageExpression()
 * @model
 * @generated
 */
public interface DefaultLanguageExpression extends LanguageExpression
{
} // DefaultLanguageExpression
