/**
 * generated by Xtext 2.22.0
 */
package org.gemoc.monilog.moniLog4DSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>External Appender</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.gemoc.monilog.moniLog4DSL.MoniLog4DSLPackage#getExternalAppender()
 * @model
 * @generated
 */
public interface ExternalAppender extends Appender
{
} // ExternalAppender
