/**
 * generated by Xtext 2.22.0
 */
package org.gemoc.monilog.moniLog4DSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lower Bound</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.gemoc.monilog.moniLog4DSL.MoniLog4DSLPackage#getLowerBound()
 * @model
 * @generated
 */
public interface LowerBound extends BoundType
{
} // LowerBound
