/**
 * generated by Xtext 2.22.0
 */
package org.gemoc.monilog.moniLog4DSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Monilogger Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.gemoc.monilog.moniLog4DSL.MoniloggerCall#getMonilogger <em>Monilogger</em>}</li>
 * </ul>
 *
 * @see org.gemoc.monilog.moniLog4DSL.MoniLog4DSLPackage#getMoniloggerCall()
 * @model
 * @generated
 */
public interface MoniloggerCall extends Action
{
  /**
   * Returns the value of the '<em><b>Monilogger</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Monilogger</em>' reference.
   * @see #setMonilogger(MoniLogger)
   * @see org.gemoc.monilog.moniLog4DSL.MoniLog4DSLPackage#getMoniloggerCall_Monilogger()
   * @model
   * @generated
   */
  MoniLogger getMonilogger();

  /**
   * Sets the value of the '{@link org.gemoc.monilog.moniLog4DSL.MoniloggerCall#getMonilogger <em>Monilogger</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Monilogger</em>' reference.
   * @see #getMonilogger()
   * @generated
   */
  void setMonilogger(MoniLogger value);

} // MoniloggerCall
