/**
 * generated by Xtext 2.22.0
 */
package org.gemoc.monilog.moniLog4DSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Moni Log Spec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.gemoc.monilog.moniLog4DSL.MoniLogSpec#getName <em>Name</em>}</li>
 *   <li>{@link org.gemoc.monilog.moniLog4DSL.MoniLogSpec#getLevel <em>Level</em>}</li>
 *   <li>{@link org.gemoc.monilog.moniLog4DSL.MoniLogSpec#getEvents <em>Events</em>}</li>
 *   <li>{@link org.gemoc.monilog.moniLog4DSL.MoniLogSpec#getConditions <em>Conditions</em>}</li>
 *   <li>{@link org.gemoc.monilog.moniLog4DSL.MoniLogSpec#getActions <em>Actions</em>}</li>
 * </ul>
 *
 * @see org.gemoc.monilog.moniLog4DSL.MoniLog4DSLPackage#getMoniLogSpec()
 * @model
 * @generated
 */
public interface MoniLogSpec extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.gemoc.monilog.moniLog4DSL.MoniLog4DSLPackage#getMoniLogSpec_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.gemoc.monilog.moniLog4DSL.MoniLogSpec#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Level</b></em>' attribute.
   * The literals are from the enumeration {@link org.gemoc.monilog.moniLog4DSL.LogLevel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Level</em>' attribute.
   * @see org.gemoc.monilog.moniLog4DSL.LogLevel
   * @see #setLevel(LogLevel)
   * @see org.gemoc.monilog.moniLog4DSL.MoniLog4DSLPackage#getMoniLogSpec_Level()
   * @model
   * @generated
   */
  LogLevel getLevel();

  /**
   * Sets the value of the '{@link org.gemoc.monilog.moniLog4DSL.MoniLogSpec#getLevel <em>Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Level</em>' attribute.
   * @see org.gemoc.monilog.moniLog4DSL.LogLevel
   * @see #getLevel()
   * @generated
   */
  void setLevel(LogLevel value);

  /**
   * Returns the value of the '<em><b>Events</b></em>' containment reference list.
   * The list contents are of type {@link org.gemoc.monilog.moniLog4DSL.Event}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Events</em>' containment reference list.
   * @see org.gemoc.monilog.moniLog4DSL.MoniLog4DSLPackage#getMoniLogSpec_Events()
   * @model containment="true"
   * @generated
   */
  EList<Event> getEvents();

  /**
   * Returns the value of the '<em><b>Conditions</b></em>' containment reference list.
   * The list contents are of type {@link org.gemoc.monilog.moniLog4DSL.Condition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions</em>' containment reference list.
   * @see org.gemoc.monilog.moniLog4DSL.MoniLog4DSLPackage#getMoniLogSpec_Conditions()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getConditions();

  /**
   * Returns the value of the '<em><b>Actions</b></em>' containment reference list.
   * The list contents are of type {@link org.gemoc.monilog.moniLog4DSL.Action}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' containment reference list.
   * @see org.gemoc.monilog.moniLog4DSL.MoniLog4DSLPackage#getMoniLogSpec_Actions()
   * @model containment="true"
   * @generated
   */
  EList<Action> getActions();

} // MoniLogSpec
