/*
 * generated by Xtext 2.22.0
 */
package org.gemoc.monilog.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.gemoc.monilog.ui.internal.MonilogActivator;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MoniLog4DSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(MonilogActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		MonilogActivator activator = MonilogActivator.getInstance();
		return activator != null ? activator.getInjector(MonilogActivator.ORG_GEMOC_MONILOG_MONILOG4DSL) : null;
	}

}
