/**
 * generated by Xtext 2.21.0
 */
package org.gemoc.monilog.moniLog.impl;

import org.eclipse.emf.ecore.EClass;

import org.gemoc.monilog.moniLog.ExactBound;
import org.gemoc.monilog.moniLog.MoniLogPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Exact Bound</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExactBoundImpl extends BoundTypeImpl implements ExactBound
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExactBoundImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MoniLogPackage.Literals.EXACT_BOUND;
  }

} //ExactBoundImpl
