/**
 * generated by Xtext 2.21.0
 */
package org.gemoc.monilog.moniLog.impl;

import org.eclipse.emf.ecore.EClass;

import org.gemoc.monilog.moniLog.ExternalAppender;
import org.gemoc.monilog.moniLog.MoniLogPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>External Appender</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExternalAppenderImpl extends AppenderImpl implements ExternalAppender
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExternalAppenderImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MoniLogPackage.Literals.EXTERNAL_APPENDER;
  }

} //ExternalAppenderImpl
