/**
 * generated by Xtext 2.21.0
 */
package org.gemoc.monilog.moniLog.impl;

import org.eclipse.emf.ecore.EClass;

import org.gemoc.monilog.moniLog.MoniLogPackage;
import org.gemoc.monilog.moniLog.UpperBound;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Upper Bound</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class UpperBoundImpl extends BoundTypeImpl implements UpperBound
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UpperBoundImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MoniLogPackage.Literals.UPPER_BOUND;
  }

} //UpperBoundImpl
