/*
 * generated by Xtext 2.22.0
 */
package org.gemoc.monilog.validation;


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class MoniLog4DSLValidator extends AbstractMoniLog4DSLValidator {
	
}
