/**
 * generated by Xtext 2.22.0
 */
package org.gemoc.monilog.moniLog4DSL.impl;

import org.eclipse.emf.ecore.EClass;

import org.gemoc.monilog.moniLog4DSL.BeforeAfterEvent;
import org.gemoc.monilog.moniLog4DSL.MoniLog4DSLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Before After Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BeforeAfterEventImpl extends EventImpl implements BeforeAfterEvent
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BeforeAfterEventImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MoniLog4DSLPackage.Literals.BEFORE_AFTER_EVENT;
  }

} //BeforeAfterEventImpl
