/**
 * generated by Xtext 2.22.0
 */
package org.gemoc.monilog.moniLog4DSL.impl;

import org.eclipse.emf.ecore.EClass;

import org.gemoc.monilog.moniLog4DSL.DefaultLanguageExpression;
import org.gemoc.monilog.moniLog4DSL.MoniLog4DSLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Default Language Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DefaultLanguageExpressionImpl extends LanguageExpressionImpl implements DefaultLanguageExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DefaultLanguageExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MoniLog4DSLPackage.Literals.DEFAULT_LANGUAGE_EXPRESSION;
  }

} //DefaultLanguageExpressionImpl
