/**
 * generated by Xtext 2.22.0
 */
package org.gemoc.monilog.moniLog4DSL.impl;

import org.eclipse.emf.ecore.EClass;

import org.gemoc.monilog.moniLog4DSL.LowerBound;
import org.gemoc.monilog.moniLog4DSL.MoniLog4DSLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Lower Bound</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class LowerBoundImpl extends BoundTypeImpl implements LowerBound
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LowerBoundImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MoniLog4DSLPackage.Literals.LOWER_BOUND;
  }

} //LowerBoundImpl
