/*
 * generated by Xtext 2.24.0
 */
package org.gemoc.monilog.resource;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.resource.impl.DefaultResourceDescriptionStrategy;
import org.eclipse.xtext.util.IAcceptor;
import org.gemoc.monilog.moniLog4DSL.Appender;
import org.gemoc.monilog.moniLog4DSL.Event;
import org.gemoc.monilog.moniLog4DSL.ExternalLayout;
import org.gemoc.monilog.moniLog4DSL.LocalLayout;
import org.gemoc.monilog.moniLog4DSL.MoniLogger;

public class MoniLog4DSLAbstractResourceDescriptionStrategy extends DefaultResourceDescriptionStrategy {
	public boolean createEObjectDescriptions(EObject eObject, IAcceptor<IEObjectDescription> acceptor) {
		if(eObject instanceof Appender) {
			return createEObjectDescriptionsForAppender(eObject, acceptor);
		}
		if(eObject instanceof LocalLayout) {
			return createEObjectDescriptionsForLocalLayout(eObject, acceptor);
		}
		if(eObject instanceof ExternalLayout) {
			return createEObjectDescriptionsForExternalLayout(eObject, acceptor);
		}
		if(eObject instanceof MoniLogger) {
			return createEObjectDescriptionsForMoniLogger(eObject, acceptor);
		}
		if(eObject instanceof Event) {
			return createEObjectDescriptionsForEvent(eObject, acceptor);
		}
		return true;
	}

	protected boolean createEObjectDescriptionsForAppender(EObject eObject, IAcceptor<IEObjectDescription> acceptor) {
		return super.createEObjectDescriptions(eObject, acceptor);
	}
	protected boolean createEObjectDescriptionsForLocalLayout(EObject eObject, IAcceptor<IEObjectDescription> acceptor) {
		return super.createEObjectDescriptions(eObject, acceptor);
	}
	protected boolean createEObjectDescriptionsForExternalLayout(EObject eObject, IAcceptor<IEObjectDescription> acceptor) {
		return super.createEObjectDescriptions(eObject, acceptor);
	}
	protected boolean createEObjectDescriptionsForMoniLogger(EObject eObject, IAcceptor<IEObjectDescription> acceptor) {
		return super.createEObjectDescriptions(eObject, acceptor);
	}
	protected boolean createEObjectDescriptionsForEvent(EObject eObject, IAcceptor<IEObjectDescription> acceptor) {
		return super.createEObjectDescriptions(eObject, acceptor);
	}
}
