/*
 * generated by Xtext 2.21.0
 */
package org.gemoc.monilog.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class MoniLogUiModule extends AbstractMoniLogUiModule {
}
