/**
 * generated by Xtext 2.21.0
 */
package org.gemoc.monilog.moniLog;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>External Layout</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.gemoc.monilog.moniLog.MoniLogPackage#getExternalLayout()
 * @model
 * @generated
 */
public interface ExternalLayout extends Layout
{
} // ExternalLayout
