/**
 * generated by Xtext 2.21.0
 */
package org.gemoc.monilog.moniLog;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Globally</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.gemoc.monilog.moniLog.MoniLogPackage#getGlobally()
 * @model
 * @generated
 */
public interface Globally extends Scope
{
} // Globally
