/**
 * generated by Xtext 2.21.0
 */
package org.gemoc.monilog.moniLog;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Layout Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.gemoc.monilog.moniLog.LayoutCall#getLayout <em>Layout</em>}</li>
 *   <li>{@link org.gemoc.monilog.moniLog.LayoutCall#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see org.gemoc.monilog.moniLog.MoniLogPackage#getLayoutCall()
 * @model
 * @generated
 */
public interface LayoutCall extends CallArgument
{
  /**
   * Returns the value of the '<em><b>Layout</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Layout</em>' reference.
   * @see #setLayout(Layout)
   * @see org.gemoc.monilog.moniLog.MoniLogPackage#getLayoutCall_Layout()
   * @model
   * @generated
   */
  Layout getLayout();

  /**
   * Sets the value of the '{@link org.gemoc.monilog.moniLog.LayoutCall#getLayout <em>Layout</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Layout</em>' reference.
   * @see #getLayout()
   * @generated
   */
  void setLayout(Layout value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link org.gemoc.monilog.moniLog.CallArgument}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see org.gemoc.monilog.moniLog.MoniLogPackage#getLayoutCall_Args()
   * @model containment="true"
   * @generated
   */
  EList<CallArgument> getArgs();

} // LayoutCall
