/**
 * generated by Xtext 2.21.0
 */
package org.gemoc.monilog.moniLog;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.gemoc.monilog.moniLog.MoniLogExpression#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @see org.gemoc.monilog.moniLog.MoniLogPackage#getMoniLogExpression()
 * @model
 * @generated
 */
public interface MoniLogExpression extends Expression
{
  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(SimpleExpression)
   * @see org.gemoc.monilog.moniLog.MoniLogPackage#getMoniLogExpression_Expression()
   * @model containment="true"
   * @generated
   */
  SimpleExpression getExpression();

  /**
   * Sets the value of the '{@link org.gemoc.monilog.moniLog.MoniLogExpression#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(SimpleExpression value);

} // MoniLogExpression
