/**
 * generated by Xtext 2.21.0
 */
package org.gemoc.monilog.moniLog;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameter Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.gemoc.monilog.moniLog.ParameterDecl#getParameters <em>Parameters</em>}</li>
 *   <li>{@link org.gemoc.monilog.moniLog.ParameterDecl#getVarArgs <em>Var Args</em>}</li>
 * </ul>
 *
 * @see org.gemoc.monilog.moniLog.MoniLogPackage#getParameterDecl()
 * @model
 * @generated
 */
public interface ParameterDecl extends EObject
{
  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link org.gemoc.monilog.moniLog.Parameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see org.gemoc.monilog.moniLog.MoniLogPackage#getParameterDecl_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getParameters();

  /**
   * Returns the value of the '<em><b>Var Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Args</em>' containment reference.
   * @see #setVarArgs(Parameter)
   * @see org.gemoc.monilog.moniLog.MoniLogPackage#getParameterDecl_VarArgs()
   * @model containment="true"
   * @generated
   */
  Parameter getVarArgs();

  /**
   * Sets the value of the '{@link org.gemoc.monilog.moniLog.ParameterDecl#getVarArgs <em>Var Args</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Args</em>' containment reference.
   * @see #getVarArgs()
   * @generated
   */
  void setVarArgs(Parameter value);

} // ParameterDecl
