/**
 * generated by Xtext 2.21.0
 */
package org.gemoc.monilog.moniLog;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Precedence</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.gemoc.monilog.moniLog.Precedence#getPredecessor <em>Predecessor</em>}</li>
 *   <li>{@link org.gemoc.monilog.moniLog.Precedence#getSuccessor <em>Successor</em>}</li>
 * </ul>
 *
 * @see org.gemoc.monilog.moniLog.MoniLogPackage#getPrecedence()
 * @model
 * @generated
 */
public interface Precedence extends Pattern
{
  /**
   * Returns the value of the '<em><b>Predecessor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predecessor</em>' containment reference.
   * @see #setPredecessor(StreamEvent)
   * @see org.gemoc.monilog.moniLog.MoniLogPackage#getPrecedence_Predecessor()
   * @model containment="true"
   * @generated
   */
  StreamEvent getPredecessor();

  /**
   * Sets the value of the '{@link org.gemoc.monilog.moniLog.Precedence#getPredecessor <em>Predecessor</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Predecessor</em>' containment reference.
   * @see #getPredecessor()
   * @generated
   */
  void setPredecessor(StreamEvent value);

  /**
   * Returns the value of the '<em><b>Successor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Successor</em>' containment reference.
   * @see #setSuccessor(StreamEvent)
   * @see org.gemoc.monilog.moniLog.MoniLogPackage#getPrecedence_Successor()
   * @model containment="true"
   * @generated
   */
  StreamEvent getSuccessor();

  /**
   * Sets the value of the '{@link org.gemoc.monilog.moniLog.Precedence#getSuccessor <em>Successor</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Successor</em>' containment reference.
   * @see #getSuccessor()
   * @generated
   */
  void setSuccessor(StreamEvent value);

} // Precedence
