/**
 * generated by Xtext 2.21.0
 */
package org.gemoc.monilog.moniLog;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>User Event</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.gemoc.monilog.moniLog.MoniLogPackage#getUserEvent()
 * @model
 * @generated
 */
public interface UserEvent extends Event
{
} // UserEvent
